account/urls.py
"""URLs patterns."""

from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    # path('login/', views.user_login, name='login'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('password_change/', auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    # Обработчики восстановления пароля.
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

images/urls.py
"""Urla urlpatterns."""

from django.urls import path
from . import views

app_name = 'images'
urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),
]

account/models.py
"""Models."""
from django.db import models
from django.conf import settings


class Profile(models.Model):
    """Profile model."""

    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)

    def __str__(self):
        """Change line."""
        return 'Profile for user {}'.format(self.user.username)

account/forms.py
"""Forms for the accounts."""
from django import forms
from django.contrib.auth.models import User

from .models import Profile


class UserEditForm(forms.ModelForm):
    """Allows users to change first name, last name, e-mail."""

    class Meta:
        """Meta information."""

        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    """Allows you to modify additional information.

    That we save in the Profile model (date of birth and avatar).
    """

    class Meta:
        """Meta information."""

        model = Profile
        fields = ('date_of_birth', 'photo')


class LoginForm(forms.Form):
    """User authorization form."""

    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    """User registration form."""

    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)

    class Meta:
        """Meta information."""

        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        """Check if both passwords match."""
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Пароли не совпадают.')
        return cd['password2']

account/views.py
"""submissions for the application account."""

from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .forms import LoginForm, UserRegistrationForm
from .forms import UserEditForm, ProfileEditForm
from .models import Profile


@login_required
def edit(request):
    """Save profile changes."""
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,
                                       data=request.POST,
                                       files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Профиль успешно обновлен')
        else:
            messages.error(request, 'Ошибка обновления профиля')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request, 'account/edit.html',
                  {'user_form': user_form, 'profile_form': profile_form})


def register(request):
    """Register user."""
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Создаем нового пользователя, но пока не сохраняем в базу данных.
            new_user = user_form.save(commit=False)
            # Задаем пользователю зашифрованный пароль.
            new_user.set_password(user_form.cleaned_data['password'])
            # Создание профиля пользователя.
            Profile.objects.create(user=new_user)
            # Сохраняем пользователя в базе данных.
            new_user.save()
            return render(request,
                          'account/register_done.html',
                          {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request,
                  'account/register.html',
                  {'user_form': user_form})


@login_required
def dashboard(request):
    """Display desktop."""
    return render(request,
                  'account/dashboard.html',
                  {'section': 'dashboard'})


def user_login(request):
    """Authorize user."""
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'],
                                password=cd['password'])
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponse('Authenticated successfully')
            else:
                return HttpResponse('Disabled account')
        else:
            return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})

account/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static "css/base.css" %}" rel="stylesheet">
    </head>

    <body>
        <div id="header">
            <span class="logo">soc_media</span>

            {% if request.user.is_authenticated %}
                <ul class="menu">
                    <li {% if section == "dashboard" %} class="selected"{% endif %}>
                        <a href="{% url "dashboard" %}">Мой рабочий стол</a>
                    </li>
                    <li {% if section == "images" %}class="selected"{% endif %}>
                        <a href="{% url "images:list" %}">Images</a>
                    </li>
                    <li {% if section == "people" %}class="selected"{% endif %}>
                        <a href="#">People</a>
                    </li>
                </ul>
            {% endif %}

            <span class="user">
            {% if request.user.is_authenticated %}
                Привет {{ request.user.first_name }},
                <a href="{% url "logout" %}">Выход</a>
            {% else %}
                <a href="{% url "login" %}">Вход</a>
            {% endif %}
            </span>
        </div>

        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">
                        {{ message|safe }}
                    <a href="#" class="close">x</a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}

        <div id="content">
            {% block content %}{% endblock %}
        </div>

        <script
            src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
        </script>
        <script
            src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js">
        </script>

        <script>
            var csrftoken = Cookies.get('csrftoken');

            functioncsrfSafeMethod(method) {
                // Для этих методов токен не будет подставляться в заголовок.
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });


            $(document).ready(function(){
                {% block domready %}{% endblock %}
            });
        </script>
    </body>
</html>